### ISSUE TITLE
compile directions

### ISSUE THREAD

**Issue by gtxaspec** [bakueikozo/altobeam_wifi#1]
@bakueikozo, can you supply directions to compile?  I would like to test your driver, the factory supplied driver crashes then loading iptables conntrack module, so maybe it is fixed with your branch

please advise!

**Comment by bakueikozo** [comment]
Just yesterday,I have faced to these problems.
I think it caused by network structure offset. 
need to recompile kernel and remake rootfs.
Wait for progress.

**Comment by gtxaspec** [comment]
thank you.  i will wait.

for reference, I have the same issue with RTL8189FTV, but I found a driver that works well for 8189 and netfilter conntrack:


```
git clone https://github.com/wens/rtl8189ES_linux
cd rtl8189ES_linux
git checkout -B rtl8189fs origin/rtl8189fs
make -j4 ARCH=mips CROSS_COMPILE=mips-linux-gnu- KSRC=../linux
```

**Comment by bakueikozo** [comment]
so, what camera do  you working ?

**Comment by gtxaspec** [comment]
wyze camera v2, v3,  and PANv2.

**Comment by gtxaspec** [comment]
the one with atbm chip is wyze PANv2

**Comment by gtxaspec** [comment]
it looks like WYZE upgraded the V3, latest versions use atbm also instead of 8189ftv, a surprise here.

**Comment by differentshades786** [comment]
Hi, I have a question, is this for the Comcast wifi dongle?

**Comment by bakueikozo** [comment]
I don't know comcast wifi dongle's spec , but  this source is for altbeam's wifi chip on ATOMCam ,connected internal SDIO.
USB mode has not tested.

**Comment by differentshades786** [comment]
Thank you for your reply. When the Comcast wifi adapter wu817n is plugged into the raspberry pi, it comes up as altobeam. Can't find suitable Linux drivers, yours looked promising, I just don't know how to install them on the PI.

**Comment by gtxaspec** [comment]
can you open it? what alto beam chipset is it?  https://github.com/OpenIPC/atbm_60xx supports some altobeam usb

**Comment by differentshades786** [comment]
It's a sealed  unit, which I'd rather not try to open. But my searches have led me to believe it's atbm6431 chipset

I'll take a look at the link you provided. Thanks again
